CardHand initial prototype
NitorInc/NitoriWare pull request #291
Opened 2018-10-07 16:26 UTC by Bottersnike

Currently using programmer art™ as placeholders, and probably has quite a few problems that'll need addressed, but I won't know unless I PR ;)

2018-10-18 01:04 UTC, dichotomousCreator requested changes
Hey guys, just adding a quick review to this PR:

- Upon loading the PR, entering the microgame scene, and saving, Git reported that a change had been made: The prefab "OpponentCard" had the Name property changed to "OpponentCard1". It should be fine to just commit that change as part of the PR as it looks like the "OpponentCard" name is outdated and just didn't quite properly stick

- I'm...not entirely sure how the gameplay is working out. It appears as though you pick two cards and then auto-win, which appears to be correct based on what I can determine since your card values are always higher...but that means I can't really test whether lower values would correctly cause a loss. I'll put that down to "for the next PR" and assume the UI and basic design elements present are the scope of this branch.

- If I recall correctly, we're not allowed to use keys other than the arrow keys and the spacebar for keyboard input. This can be remedied by using the spacebar to select cards instead of the enter key.

Assuming we don't need properly prototyped gameplay yet, the spacebar thing and the recommit should do it. (If we do need gameplay you'd need to add a way to lose the hand, like some extra lower value cards in the player's selection options)

2018-10-18 10:08 UTC, Bottersnike commented
Coolio. I should be able to get most of those implemented either on this Friday or Saturday.

2018-10-20 11:36 UTC, Bottersnike commented
Made requested changes. Not sure what was up with `OpponentCard` as my local git reported it as already beeing named `OpponentCard1` in the PR'd commit.

2018-11-26 22:00 UTC, dichotomousCreator approved these changes

2018-11-28 18:59 UTC, merged