Microgame/seija spin/basic functionality
NitorInc/NitoriWare pull request #292
Opened 2018-10-07 16:37 UTC by Shadowth117

2018-10-09 04:05 UTC, dichotomousCreator requested changes
Hey guys, I'm just doing a quick sanity check review on the PR:

- There's a couple file oddities. You've committed the file "Assets/script.cs" which appears to be a default Unity script, along with a corresponding meta file. This is outside your microgame subfolder, so it'll need to be deleted (hence the "request changes" designation). Additionally, when I booted up the PR on my computer Unity auto-generated new .meta files: "Assets/Microgames/ReimuDodge.meta" and "Assets/Microgames/ReimuDodge/Scenes.meta". I'm not actually 100% on what the deal with this is, but I think something needs to be done to ensure it doesn't happen (hopefully someone else can help out with this. @Barley maybe?)

- It did take me a few tries to get the spinning gameplay down when I was testing. I figured out to click and rotate the cursor pretty fast, but it took me a couple tries to realize the direction mattered and a couple more to realize I had to make sure I was doing it actually on the character. It might also be worth looking at the edge case of the mouse moving off the character mid-spin, as this causing the spin to just instantly stop is kind of jarring (that's integral to your difficulty though so I'm not sure what if anything should even be done about it)

- If you try spinning the wrong direction it sometimes does little odd things like the character's facial expression flickering or their rotation suddenly jumping to a different value. (No winning by doing it though, so no functional issues)

That's all I really found. The presentation for this game is really top-notch, the animation, art and sound mesh well and provide a great overall aesthetic. I tried it at higher speeds and it was still possible, so no issues there.

2018-10-09 20:25 UTC, Shadowth117 commented
I believe it should be alright now. Let me know if there's any problems.

2018-10-31 22:48 UTC, dichotomousCreator approved these changes

2018-10-31 22:55 UTC, dichotomousCreator requested changes
Hi guys, sorry about this but we are actually going to require another set of changes. The current build has each animation frame as a separate sprite, and we'll need it refactored so that rather than this approach the sprites are all included in a single sprite sheet. Let me know if you have any questions or concerns with this.

2018-11-08 21:07 UTC, dichotomousCreator approved these changes

2018-11-28 18:57 UTC, merged